# Generating Data w/ Numpy

In [2]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [36]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [39]:
array_full = np.full(shape = (2,3), fill_value=1)
array_full

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
array_ones = np.ones((2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### "_like" functions

In [42]:
matrix_A = np.array([[1,0,0,2], [2,332,43,23], [112, 2,332,4]])
matrix_A

array([[  1,   0,   0,   2],
       [  2, 332,  43,  23],
       [112,   2, 332,   4]])

In [44]:
matrix_B = np.empty_like(matrix_A)
matrix_A

array([[  1,   0,   0,   2],
       [  2, 332,  43,  23],
       [112,   2, 332,   4]])

In [45]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]