# Numpy Fundamentals

In [2]:
import numpy as np

## Indexing

In [4]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values 

In [5]:
array_a[0]

array([1, 2, 3])

In [7]:
array_a[:, 0]

array([1, 4])

### Negative Indices

In [8]:
array_a[-1]

array([4, 5, 6])

### Assigning Values

In [10]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [12]:
array_a[1] = 7
array_a

array([[9, 9, 9],
       [7, 7, 7]])

In [13]:
type(array_a)

numpy.ndarray