In [2]:
import numpy as np

## Declaring, scalars, vectors, and matrices 

### Scalars

In [3]:
s = 5

In [4]:
s

5

### Vectors

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

### Matrices 

In [7]:
m = np.array([[5,12,6], [-3,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [12]:
s_array = np.array(5)
s_array

array(5)

In [13]:
type(s_array)

numpy.ndarray

## Data Shapes

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

In [16]:
v.reshape(1, 3)

array([[ 5, -2,  4]])

v.reshape(3,1)

In [17]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
s_array.shape

## Add/subtract Matrices 

In [18]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [19]:
m+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [20]:
m.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])